//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webRenap.wsRenapCertificado {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persona", Namespace="http://schemas.datacontract.org/2004/07/wsRenap")]
    [System.SerializableAttribute()]
    public partial class Persona : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CUIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GeneroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LugarNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObervacionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrimerApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrimerNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SegundoApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SegundoNombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CUI {
            get {
                return this.CUIField;
            }
            set {
                if ((object.ReferenceEquals(this.CUIField, value) != true)) {
                    this.CUIField = value;
                    this.RaisePropertyChanged("CUI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((this.FechaNacimientoField.Equals(value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Genero {
            get {
                return this.GeneroField;
            }
            set {
                if ((object.ReferenceEquals(this.GeneroField, value) != true)) {
                    this.GeneroField = value;
                    this.RaisePropertyChanged("Genero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Log {
            get {
                return this.LogField;
            }
            set {
                if ((object.ReferenceEquals(this.LogField, value) != true)) {
                    this.LogField = value;
                    this.RaisePropertyChanged("Log");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LugarNacimiento {
            get {
                return this.LugarNacimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.LugarNacimientoField, value) != true)) {
                    this.LugarNacimientoField = value;
                    this.RaisePropertyChanged("LugarNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Obervaciones {
            get {
                return this.ObervacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.ObervacionesField, value) != true)) {
                    this.ObervacionesField = value;
                    this.RaisePropertyChanged("Obervaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimerApellido {
            get {
                return this.PrimerApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimerApellidoField, value) != true)) {
                    this.PrimerApellidoField = value;
                    this.RaisePropertyChanged("PrimerApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimerNombre {
            get {
                return this.PrimerNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimerNombreField, value) != true)) {
                    this.PrimerNombreField = value;
                    this.RaisePropertyChanged("PrimerNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SegundoApellido {
            get {
                return this.SegundoApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.SegundoApellidoField, value) != true)) {
                    this.SegundoApellidoField = value;
                    this.RaisePropertyChanged("SegundoApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SegundoNombre {
            get {
                return this.SegundoNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.SegundoNombreField, value) != true)) {
                    this.SegundoNombreField = value;
                    this.RaisePropertyChanged("SegundoNombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsRenapCertificado.ICertificado")]
    public interface ICertificado {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICertificado/Certificado", ReplyAction="http://tempuri.org/ICertificado/CertificadoResponse")]
        webRenap.wsRenapCertificado.Persona Certificado(string CUI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICertificado/Certificado", ReplyAction="http://tempuri.org/ICertificado/CertificadoResponse")]
        System.Threading.Tasks.Task<webRenap.wsRenapCertificado.Persona> CertificadoAsync(string CUI);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICertificadoChannel : webRenap.wsRenapCertificado.ICertificado, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CertificadoClient : System.ServiceModel.ClientBase<webRenap.wsRenapCertificado.ICertificado>, webRenap.wsRenapCertificado.ICertificado {
        
        public CertificadoClient() {
        }
        
        public CertificadoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CertificadoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CertificadoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CertificadoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public webRenap.wsRenapCertificado.Persona Certificado(string CUI) {
            return base.Channel.Certificado(CUI);
        }
        
        public System.Threading.Tasks.Task<webRenap.wsRenapCertificado.Persona> CertificadoAsync(string CUI) {
            return base.Channel.CertificadoAsync(CUI);
        }
    }
}
